import type { Metadata } from "next";
import { Geist, Geist_Mono, K2D } from "next/font/google";
import "./globals.css";
import { SnackbarProvider } from "@/components/context/SnackbarContext";
import NextAuthProvider from "@/components/context/NextAuthProvider";
import HeaderBar from "@/components/HeaderBar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const k2d = K2D({
  variable: "--font-k2d",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Houston Pickleball Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {

  return (
    <html lang="en">
      <head>
        <script id="search-js" defer src="https://api.mapbox.com/search-js/v1.3.0/web.js"></script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${k2d.variable} antialiased`}
      >
        <SnackbarProvider>
          <NextAuthProvider>
            <div className="min-h-screen font-standard h-fit bg-[url('/pickle-vector-tesselation.png')] bg-repeat lg:bg-size-[30vw] bg-size-[100vw] ">
              <HeaderBar />
              {children}
            </div>
          </NextAuthProvider>
        </SnackbarProvider>
      </body>
    </html>
  );
}
