import type { Metadata } from "next";
import { Geist, Geist_Mono, K2D } from "next/font/google";
import "./globals.css";
import { SnackbarProvider } from "@/components/context/SnackbarContext";
import { getSession, SessionProvider } from "next-auth/react";
import NextAuthProvider from "@/components/context/NextAuthProvider";
import { Session } from "next-auth";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const k2d = K2D({
  variable: "--font-k2d",
  subsets: ["latin"],
  weight: "400",
})

export const metadata: Metadata = {
  title: "Houston Pickleball Hub",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children, session
}: Readonly<{
  children: React.ReactNode, session: Session | null;
}>) {

  return (
    <html lang="en">
      <head>
        <script id="search-js" defer src="https://api.mapbox.com/search-js/v1.3.0/web.js"></script>
      </head>

      <body
        className={`${geistSans.variable} ${geistMono.variable} ${k2d.variable} antialiased`}
      >
        <SnackbarProvider>
          <NextAuthProvider session={session}>
            {children}
          </NextAuthProvider>
        </SnackbarProvider>
      </body>
    </html>
  );
}
